quiz_builder/quiz_builder/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^quiz/', include('quizzes.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^register/', RedirectView.as_view(url='/quiz/register')),
    url(r'^$', RedirectView.as_view(url='/quiz/', permanent=True))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quiz_builder/quizzes/urls.py
from django.conf.urls import url

from . import views

app_name = 'quizzes'
urlpatterns = [
    url(r'^$', views.QuizListView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)$', views.QuizDetailView.as_view(), name='quiz-detail'),
    url(r'^(?P<pk>\d+)/take/', views.take_quiz, name='take-quiz'),
    url(r'^(?P<quiz_pk>\d+)/results/', views.quiz_results, name='quiz-results'),
]

quiz_builder/quizzes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Quiz(models.Model):
    title = models.CharField(max_length=200)
    date_created = models.DateField(auto_now_add=True)
    expiration_date = models.DateField(null=True, blank=True)

    class Meta:
        verbose_name = 'Quiz'
        verbose_name_plural = 'Quizzes'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('quizzes:quiz-detail', args=[str(self.id)])


class Question(models.Model):
    question = models.CharField(max_length=200)
    quiz = models.ForeignKey('Quiz', on_delete=models.CASCADE)

    def __str__(self):
        return self.question

    def get_quiz(self):
        return self.quiz
    get_quiz.short_description = 'Quiz'


class Choice(models.Model):
    label = models.CharField(max_length=150)
    correct = models.BooleanField(default=False)
    number_in_question = models.IntegerField(default=1)
    question = models.ForeignKey('Question', on_delete=models.CASCADE)

    def __str__(self):
        return self.label

    def get_quiz(self):
        return self.question.quiz
    get_quiz.short_description = 'Quiz'

    def save(self, *args, **kwargs):
        if self._state.adding:
            last_number_in_question = Choice.objects.filter(question=self.question).aggregate(largest=models.Max('number_in_question'))['largest']

            if last_number_in_question is not None:
                self.number_in_question = last_number_in_question + 1

        super(Choice, self).save(*args, **kwargs)


class QuizSession(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey('Quiz', on_delete=models.CASCADE)
    quiz_date_taken = models.DateField(auto_now_add=True)
    result = models.IntegerField(default=0)

    def __str__(self):
        return str(self.quiz) + ' - ' + str(self.user)


class QuizSessionAnswers(models.Model):
    quiz_session = models.ForeignKey('QuizSession', on_delete=models.CASCADE)
    question = models.ForeignKey('Question', on_delete=models.CASCADE)
    answer = models.ForeignKey('Choice', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return str(self.question) + ' - ' + str(self.answer)

quiz_builder/quizzes/forms.py
from django import forms


class QuizForm(forms.Form):

    def __init__(self, questions, quiz_pk, *args, **kwargs):
        super(QuizForm, self).__init__(*args, **kwargs)
        for index, question in enumerate(questions):
            self.fields['question_' + str(index)] = forms.ModelChoiceField(
                label=question['question'],
                queryset=question['question'].choice_set.all().order_by('number_in_question'),
                required=True, initial=1,
                widget=forms.RadioSelect()
            )
        self.fields['quiz_pk'] = forms.IntegerField(initial=quiz_pk, widget=forms.HiddenInput)

quiz_builder/quizzes/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from datetime import datetime as dt
from django.urls import reverse
from django.http import HttpResponse

from .models import Quiz, QuizSession, QuizSessionAnswers
from .forms import QuizForm


@login_required
def quiz_results(request, quiz_pk):
    quiz = get_object_or_404(Quiz, pk=quiz_pk)
    session = QuizSession.objects.filter(user=request.user, quiz=quiz)
    if session.count() < 1:
        return redirect(reverse('quizzes:quiz-detail', args=[str(quiz.id)]), {
            'error_message': 'You have not taken this quiz yet. Want to try it out?'
        })
    else:
        user_results = []
        all_questions = session[0].quiz.question_set.all()
        for index, question in enumerate(all_questions):
            correct_answer = question.choice_set.filter(correct=True)[0]
            user_answer = session[0].quizsessionanswers_set.all()[index].answer
            user_results.append({
                'question': question,
                'correct_answer': correct_answer,
                'user_answer': user_answer,
                'correct': correct_answer == user_answer,
                'choices': question.choice_set.all()
            })
        total_questions = all_questions.count()
        return render(
            request,
            'quizzes/quiz_result.html',
            context={
                'results': user_results,
                'quiz': quiz,
                'score': session[0].result,
                'total_questions': total_questions
            }
        )


# Create your views here.
@login_required
def take_quiz(request, pk):
    quiz = get_object_or_404(Quiz, pk=pk)
    session = QuizSession.objects.filter(user=request.user, quiz=quiz)
    print(session)
    if session.count() < 1:
        questions = []
        for question in quiz.question_set.all():
            choices = question.choice_set.all()
            answers = choices.filter(correct=True)
            questions.append({
                'question': question,
                'choices': choices,
                'answers': answers
            })

        if quiz.expiration_date is not None and dt.now().date() > quiz.expiration_date:
            return redirect(reverse('quizzes:index'),
                            {'error_message': 'You cannot take this quiz because it has expired.'})

        if request.method == 'POST':
            score = 0
            answers = []
            form = QuizForm(questions, quiz.id, data=request.POST)
            if form.is_valid():
                for index, question in enumerate(questions):
                    correct_choice = question['question'].choice_set.filter(correct=True)[0]
                    user_choice = form.cleaned_data['question_' + str(index)]
                    if user_choice.pk == correct_choice.pk:
                        score += 1
                    answers.append({
                        'question': question['question'],
                        'answer': user_choice
                    })
                new_quiz_session = QuizSession(
                    user=request.user,
                    quiz_date_taken=dt.now().date,
                    result=score,
                    quiz=quiz
                )
                new_quiz_session.save()
                for answer in answers:
                    new_quiz_session_answer = QuizSessionAnswers(
                        quiz_session=new_quiz_session,
                        question=answer['question'],
                        answer=answer['answer']
                    )
                    new_quiz_session_answer.save()
                return redirect(reverse('quizzes:quiz-results', args=[str(quiz.id)]))

        form = QuizForm(questions, quiz.id)
        return render(request, 'quizzes/quiz_take.html', context={
            'quiz': quiz,
            'form': form
        })
    else:
        return redirect(reverse('quizzes:quiz-results', args=[str(quiz.id)]))


class QuizListView(generic.ListView):
    model = Quiz
    paginate_by = 20
    ordering = ['date_created']

    def get_context_data(self, **kwargs):
        context = super(QuizListView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            sessions = QuizSession.objects.filter(user=self.request.user).order_by('-quiz_date_taken')
            quiz_list = []
            for session in sessions:
                quiz_list.append({
                    'quiz': session.quiz,
                    'url': session.quiz.get_absolute_url()
                })
            print(quiz_list[:10])
            context['user_quiz_list'] = quiz_list[:10]
        return context


class QuizDetailView(generic.DetailView):
    model = Quiz

    def get_context_data(self, **kwargs):
        context = super(QuizDetailView, self).get_context_data(**kwargs)
        context['number_of_questions'] = self.object.question_set.count()
        return context

quiz_builder/quizzes/templates/quizzes/quiz_detail.html
{% extends 'base.html' %}
{% block content %}
    <h1>Quiz: {{ quiz }}</h1>
    <p>
        This quiz has {{ number_of_questions }}
        {% if number_of_questions > 1 %}
            questions.
        {% else %}
            question.
        {% endif %}
    </p>
    <a class="btn btn-default" href="{% url 'quizzes:take-quiz' quiz.id %}">Take Quiz</a>
{% endblock %}

quiz_builder/quizzes/templates/quizzes/quiz_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>Welcome to the Quiz App!</h1>
        <h2>List of Quizzes:</h2>
        <ul>
            {% for quiz in quiz_list %}
                <li><a href="{{ quiz.get_absolute_url }}">{{ quiz }}</a></li>
            {% endfor %}
        </ul>
        {% if user.is_authenticated %}
            <h2>Most recently taken quizzes:</h2>
            <ul>
                {% for quiz in user_quiz_list %}
                    <li><a href="{{ quiz.url }}">{{ quiz.quiz }}</a></li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

quiz_builder/quizzes/templates/quizzes/quiz_result.html
{% extends 'base.html' %}

{% block content %}
    <h2>Quiz Results: {{ quiz }}</h2>
    {% for result in results %}
        <div class="alert alert-{% if result.correct %}success{% else %}danger{% endif %}">Question: {{ result.question }}</div>
        <div>
            <p>Choices:</p>
            <ul>
                {% for choice in result.choices %}
                    <li>
                        {{ choice }}
                        {% if result.user_answer == choice %} - YOUR ANSWER{% endif %}
                    </li>
                {% endfor %}
            </ul>
            <p>Correct Answer: {{ result.correct_answer }}</p>
        </div>
    {% endfor %}
    <div>
        <h4>Your Score: {{ score }} out of {{ total_questions }} questions</h4>
    </div>

{% endblock %}

quiz_builder/quizzes/templates/quizzes/quiz_take.html
{% extends 'base.html' %}
{% block content %}
    <h1>Taking Quiz: {{ quiz }}</h1>
    <div class="container">
        <form method="post" action="{{ request_path }}">
            {% csrf_token %}
            {{ form.as_ul }}
            <button class="btn btn-default" type="submit">Submit</button>
        </form>
    </div>
{% endblock %}